# Generated by Django 5.0.2 on 2024-07-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
