# Generated by Django 5.0.2 on 2024-07-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_register_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
